version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/.github/"
    schedule:
      interval: "weekly"
    target-branch: kirkstone
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: kirkstone
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: dunfell

